#include<stdio.h>
#include<stdlib.h>
#include<SDL2/SDL.h>

int main(){

    FILE *in = stdin;

    char* p_throwaway = calloc(1000, sizeof(char));

    // the first line in a ppm file (specification P3 or P6)
    fgets(p_throwaway, 1000, in);

    // second line in a ppm file is a comment
    fgets(p_throwaway, 1000, in);


    // third line contains the image dimensions.
    char* p_dimensions = calloc(1000, sizeof(char));
    fgets(p_dimensions, 1000, in);

    int width = -1;
    int height = -1;

    sscanf(p_dimensions, "%d %d\n", &width, &height);

    free(p_dimensions);

    printf("width=%d, height=%d\n", width, height);

    // forth line in a ppm file is a max value for rgb
    fgets(p_throwaway, 1000, in);

    free(p_throwaway);


    SDL_Window *p_window = SDL_CreateWindow("Image Viewer", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, width, height, 0);

    SDL_Surface *p_surface = SDL_GetWindowSurface(p_window);

    SDL_Rect pixel = (SDL_Rect){0, 0, 1, 1};
    Uint32 color = 0;

    for(int y=0; y<height; y++){
        for(int x=0; x<width; x++){
            Uint8 r, g, b;
            r = (char) getchar();
            g = (char) getchar();
            b = (char) getchar();

            color =  SDL_MapRGB(p_surface->format, r, g, b);

            pixel.x = x;
            pixel.y = y;

            SDL_FillRect(p_surface, &pixel, color);   // SDL_FillRect accepts color in Uint32 format. Uint32 can be generated by SDL_MapRGB();

        }
    }


    SDL_UpdateWindowSurface(p_window);
    
    int app_running = 1;
    while (app_running){
        SDL_Event event;
        while (SDL_PollEvent(&event)){
            if (event.type == SDL_QUIT){
                app_running = 0;
            }
        }
        SDL_Delay(100);
    }

    return 0;
}
